# Easywp plugin feature flags file
# This file is used to enable or disable features of the Easywp plugin
# The file is in YAML format
# You can find more information about YAML here: https://yaml.org/
#
# The version of the file is 1.0.0
version: "1.0.0"
hackguardian:
  # Enable or disable the HackGuardian feature
  enabled: true
  # Request timeout
  timeout: 0
  # API route
  route: "/v1/readonly"
monarx:
  # Enable or disable the Monarx feature
  enabled: true
  # Throttle request time in minutes
  # By setting this value to 0, the feature will be disabled
  throttle: 5
  # Request timeout
  timeout: 0
  # API route
  route: "/v1/sequoia-app-webhook/api/v1alpha1/notifications"